version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:jammy-20211029
   steps:
      - run:
          command: |
            git clone https://github.com/missgoin/kernel_xiaomi_lavender.git  -b oldcam builder_kernel --depth=1
            cd builder_kernel
            cp -af sources.list /etc/apt/
            cp -af 99own /etc/apt/apt.conf.d/
            apt update && apt upgrade -y
            ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
            apt install -f -y git bison flex libxml2 libssl-dev bc zip ccache p7zip default-jre python3 python3-pip wget curl
            bash .circleci/lavender1.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
