name: WTC2 BUILD

on:
  workflow_dispatch:
  
env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      GIT_SECRET: ${{ secrets.GIT_SECRET }}
      GIT_SECRETB: ${{ secrets.GIT_SECRETB }}
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      SDCLANGPASS: ${{ secrets.SDCLANGPASS }}
      #GDRIVEKEYPASS: ${{ secrets.GDRIVEKEYPASS }}
      
#on: [push]

jobs:
  kernel-build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy-20211029
    steps:
    - uses: actions/checkout@v2
    - name: Setup CI
      run: |
        apt update && apt upgrade -y
        ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
        apt install -f -y git bison flex libxml2 libssl-dev bc zip ccache p7zip default-jre python3 python3-pip wget curl
        git clone https://github.com/missgoin/kernel_xiaomi_lavender.git  -b oldcam builder_kernel --depth=1
        cd builder_kernel
        cp -af sources.list /etc/apt/
        cp -af 99own /etc/apt/apt.conf.d/
    - name: Setup and Build Kernel
      run: bash .circleci/lavender1.sh
