name: Kernel_3
on:
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest
      #container:
      #image: ubuntu:jammy-20211029

    steps:
    - name: setting konfigurasi
      uses: actions/checkout@v3

    - name: setup environment
      run: |
          sudo apt-get update --fix-missing
          sudo apt-get install git make bc bison \
          cpio gcc llvm lld g++-multilib python2 clang git libxml2 python3-pip gcc llvm lld g++-multilib clang default-jre git automake lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng bc libstdc++6 libncurses5 wget python3 python3-pip gcc clang libssl-dev rsync flex git-lfs libz3-dev libz3-4 axel tar bc binutils-dev bison build-essential ca-certificates ccache clang cmake curl file flex git libelf-dev libssl-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev && python3 -m pip install networkx && pip3 install --upgrade gupload
          
          sudo apt-get update --fix-missing
          sudo apt-get install git make bc bison \
          openssl curl zip kmod cpio flex libelf-dev \
          libssl-dev libtfm-dev wget device-tree-compiler \
          ca-certificates python3 python2 binutils \
          binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi \
          libghc-libyaml-dev libyaml-devglibc-source
          
    - name: ready compile...
      run: |
          curl https://raw.githubusercontent.com/missgoin/hub/main/wtc2.sh > wtc2.sh
          chmod +x wtc2.sh
          bash wtc2.sh
      shell: bash
     # env:
     #    CHATID: ${{ secrets.CHAT_ID }}
     #    API_BOT: ${{ secrets.BOT_API }}
     #    TYPE_KERNEL: ${{ secrets.EZA }}
