name: Kernel_2
on:
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-20.04

    steps:
    - name: setting konfigurasi
      uses: actions/checkout@v3

    - name: setup environment
      run: |
      
        #cp -af sources.list /etc/apt/
        #cp -af 99own /etc/apt/apt.conf.d/
        #apt update && apt upgrade -y
        #ln -fs /usr/share/zoneinfo/Asia/Bangkok /etc/localtime && date
        #apt install -f -y git bison flex libxml2 libssl-dev bc zip ccache p7zip default-jre python3 python3-pip wget curl
      
        sudo apt-get update --fix-missing
        sudo apt-get install git make bc bison \
          openssl curl zip kmod cpio flex libelf-dev \
          libssl-dev libtfm-dev wget device-tree-compiler \
          ca-certificates python3 python2 binutils \
          binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi \
          libghc-libyaml-dev libyaml-dev
          #glibc-source 
          
        sudo apt-get install gawk bison gcc make -y
        sudo wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.35.tar.gz
        sudo tar -zxvf glibc-2.35.tar.gz && cd glibc-2.35
        sudo mkdir glibc-build && cd glibc-build
        sudo ../configure --prefix=/opt/glibc
        sudo make
        sudo make install
          
    - name: ready compile...
      run: |
          curl https://raw.githubusercontent.com/missgoin/hub/main/wtc2.sh > wtc2.sh
          chmod +x wtc2.sh
          bash wtc2.sh
      shell: bash
